#!/bin/sh

girdershealthcheckurl=http://192.168.100.193/healthcheck

echo '<<<girdershealthcheck>>>'
echo ${girdershealthcheckurl}.html
curl --max-redirs 4 --silent ${girdershealthcheckurl}.json | jq '.'
