#!/usr/bin/python


def inventory_nshield_stats(checkname, info):
    #import pprint; pprint.pprint(info)
    return [(None, None, None)]

def check_nshield_stats(item, no_params, info):
    try:
        cmdCountAll = int(info[0][0])
        cmdBytesAll = int(info[0][1])
        cmdErrorsAll = int(info[0][2])
        replyCountAll = int(info[0][3])
        replyBytesAll = int(info[0][4])
        replyErrorsAll = int(info[0][5])
        code = 0
        if (cmdErrorsAll > 0): code = 1;
        if (replyErrorsAll > 0): code = 1;
        ret = (code, "nShield Stats", [
                ("cmdCountAll", cmdCountAll), 
                ("cmdBytesAll", cmdBytesAll), 
                ("cmdErrorsAll", cmdErrorsAll), 
                ("replyCountAll", replyCountAll), 
                ("replyBytesAll", replyBytesAll), 
                ("replyErrorsAll", replyErrorsAll),
                ])              
        #, ()
        #import pprint; pprint.pprint(ret)
        return ret
    except:
        return (3, "UNKNOWN - No SNMP Output from Agent", [])

check_info['nshield_stats'] = {
    'check_function'            : check_nshield_stats,
    'inventory_function'        : inventory_nshield_stats,
    'service_description'       : "nShield Hardserver",
    'has_perfdata'              : True,
    'snmp_scan_function'        : lambda oid: oid('.1.3.6.1.4.1.7682.2.50.16') != None,
    'snmp_info'                 : ( ".1.3.6.1.4.1.7682.2.51", [ 
                                    "3.0",  # cmdCountAll
                                    "4.0", # cmdBytesAll
                                    "5.0", # cmdErrorsAll
                                    "6.0", # replyCountAll
                                    "7.0", # replyBytesAll
                                    "8.0" # replyErrorsAll 
                                    ]),
}




