#!/usr/bin/python

# OIDs used:
# THALES-PAYSHIELD::ps9000LmkNumLoaded.0            	.1.3.6.1.4.1.4096.2.2.9000.4.1.0
# THALES-PAYSHIELD::ps9000LmkNumTestLmksLoaded.0 	.1.3.6.1.4.1.4096.2.2.9000.4.2.0
# THALES-PAYSHIELD::ps9000LmkNumOldLmksLoaded.0     	.1.3.6.1.4.1.4096.2.2.9000.4.3.0
# THALES-PAYSHIELD::ps9000LmkStatusLoaded.x   		.1.3.6.1.4.1.4096.2.2.9000.4.4.1.2.1
# THALES-PAYSHIELD::ps9000LmkStatusAuth.x		.1.3.6.1.4.1.4096.2.2.9000.4.4.1.3.1
# THALES-PAYSHIELD::ps9000LmkStatusNumAuthActivities.x	.1.3.6.1.4.1.4096.2.2.9000.4.4.1.4.1
# THALES-PAYSHIELD::ps9000LmkStatusScheme.x		.1.3.6.1.4.1.4096.2.2.9000.4.4.1.5.1
# THALES-PAYSHIELD::ps9000LmkStatusAlgorithm.x		.1.3.6.1.4.1.4096.2.2.9000.4.4.1.6.1
# THALES-PAYSHIELD::ps9000LmkStatusLiveTest.x		.1.3.6.1.4.1.4096.2.2.9000.4.4.1.7.1
# THALES-PAYSHIELD::ps9000LmkStatusComments.1		.1.3.6.1.4.1.4096.2.2.9000.4.4.1.8.1
# THALES-PAYSHIELD::ps9000LmkStatusCheckDigits.1 	.1.3.6.1.4.1.4096.2.2.9000.4.4.1.9.1
# Scan function looks for Enterprise 'THALES-PAYSHIELD' OID and if it exists we continue

# Author: Rolf Koch - rolf.koch@netcetera.com - http://netcetera.com

def inventory_payshield_lmk(info):
    yield 'Payshield LMK Num Loaded', None
    yield 'Payshield LMK Num Test Loaded', None
    yield 'Payshield LMK Num Old Loaded', None
    for index, value in enumerate(info[0]):
        if value[3] == '1': 
            yield 'Payshield LMK Info %d' % index, None


def check_payshield_lmk(item, _no_params, info):
#    print info
    for index, value  in enumerate(info[0]):
#        print index
        numloaded, numtestloaded, numoldloaded, statusloaded, statusauth, statusnumauthactivities, statusscheme, statusalg, statuslivetest, statuscomment, statuscheckvalue = value
#        print statuscomment 
	if 'Payshield LMK Num Loaded' in item:
            return (0, "Currently there are %s LMK loaded" % numloaded)
        elif 'Payshield LMK Num Test Loaded' in item:
	    return (0, "Currently there are %s TEST LMK loaded" % numtestloaded) 
        elif 'Payshield LMK Num Old Loaded' in item:
            if int(numoldloaded) > 0:
                 return (0, "Currently there are %s OLD LMK loaded" % numoldloaded)
            else:
                 return (0, "No OLD LMK are loaded" )
        elif 'Payshield LMK Info %d' % index  in item:
            scheme = {"1" : "Unknown", "2" : "Variant", "3" : "Keyblock", "4": "Aes"}
            algorithm = {"1" : "Unknown", "2": "3Des2Key", "3": "3Des3Key", "4": "Aes256"}
            livetest = { "1" : "lmkStatusUnknown", "2" : "Live", "3": "Test" }
            return (0, "LMK %d %s %s - \nloaded %s\nAuth %s\nNumAuthActivities: %s\nScheme: \"%s\" \nAlgorithm: \"%s\"\nLiveTest: \"%s\"\nComment: \"%s\"\nCheckvalue: \"%s\"" % (index, statuscomment, statuscheckvalue, statusloaded, statusauth, statusnumauthactivities, scheme[statusscheme], algorithm[statusalg], livetest[statuslivetest], statuscomment, statuscheckvalue) )


check_info["payshield_lmk"] = {
    "check_function"        : check_payshield_lmk,
    "inventory_function"    : inventory_payshield_lmk,
    "service_description"   : "%s",
    "has_perfdata"          : False,
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.4096") and oid(".1.3.6.1.4.1.4096.2.2.9000.3.1.0") is not None ,
    "snmp_info"             : [( ".1.3.6.1.4.1.4096.2.2.9000.4", [
              			  "1.0",   # ps9000LmkNumLoaded.0
                                  "2.0",   # ps9000LmkNumTestLmksLoaded.0
                                  "3.0",   # ps9000LmkNumOldLmksLoaded.0
                                  "4.1.2", # ps9000LmkStatusLoaded.x0
                                  "4.1.3", # ps9000LmkStatusAuth.x
                                  "4.1.4", # ps9000LmkStatusNumAuthActivities.x
                                  "4.1.5", # ps9000LmkStatusScheme.x
                                  "4.1.6", # ps9000LmkStatusAlgorithm.x
                                  "4.1.7", # ps9000LmkStatusLiveTest.x
                                  "4.1.8", # ps9000LmkStatusComments.1
                                  "4.1.9"  # ps9000LmkStatusCheckDigits.1
                              ])],
}
