#!/usr/bin/python

# OIDs used:
# THALES-ESECURITY-PAYSHIELD-MIB::payShieldLogsErrorlogTotalCount.0                     .1.3.6.1.4.1.4096.2.2.10000.10.1.1.0
#
# Scan function looks for Enterprise 'THALES-ESECURITY-PAYSHIELD-MIB' OID and if it exists we continue

# Author: Rolf Koch - rolf.koch@netcetera.com - http://netcetera.com

def inventory_payshield10k_errorlog(info):
    yield 'Payshield Error Log', None

def check_payshield10k_errorlog(item, _no_params, info):
    for index, value  in enumerate(info[0]):
        errorraw=value
        error = int(errorraw[0])
        if 'Payshield Error Log'  in item:
            if error >= 1:
                return (0, "Errors found in errorlog: %s errors" % error, [ ( "error", error), ] )
            else:
                return (0, "No Errors found in errorlog: %s errors" % error , [ ( "error", error), ] )

check_info["payshield10k_errorlog"] = {
    "check_function"        : check_payshield10k_errorlog,
    "inventory_function"    : inventory_payshield10k_errorlog,
    "service_description"   : "%s",
    "has_perfdata"          : True,
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.4096") and oid(".1.3.6.1.4.1.4096.2.2.10000.2.1.0") is not None ,
    "snmp_info"             : [( ".1.3.6.1.4.1.4096.2.2.10000", [
                                  "10.1.1.0",   # payShieldLogsErrorlogTotalCount.0
                              ])],
}

